version: '3'
services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=mycluster
    volumes:
      - cassandra-data:/var/lib/cassandra

  app:
    image: bs6/732-project-image
    depends_on:
      - cassandra
    environment:
      - CASSANDRA_HOST=cassandra
    ports:
      - "8080:8080"

volumes:
  cassandra-data:
